services:
  kafka:
    image: bitnamilegacy/kafka:3.4
    ports:
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_KRAFT_CLUSTER_ID=T_MQRL2xTU-ACKPcnb-KBQ
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://127.0.0.1:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true

  ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_NAME=kraft

  redis:
    image: redis:8.6-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
    restart: always

  postgres-migrate:
    profiles:
      - tools
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:postgres:5432
    ports:
      - "127.0.0.1:5432:5432"

  swagger:
    profiles:
      - tools
    build:
      context: ${PROJECT_ROOT}
      dockerfile_inline: |
        FROM golang:1.25.6-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - ${PROJECT_ROOT}:/code

  history-service:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
      args:
        - SERVICE=history-service
    container_name: history-service
    env_file:
      - ${PROJECT_ROOT}/history-service/.env
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    restart: always

  api-gateway:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
      args:
        - SERVICE=api-gateway
    container_name: api-gateway
    env_file:
      - ${PROJECT_ROOT}/api-gateway/.env
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    ports:
      - "8081:8081"
    restart: always

  notification-worker:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
      args:
        - SERVICE=notification-worker
    container_name: notification-worker
    env_file:
      - ${PROJECT_ROOT}/notification-worker/.env
    volumes:
      - ${PROJECT_ROOT}/out/logs:/app/out/logs
    restart: always
