// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/notification/v1/history.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationStatus int32

const (
	NotificationStatus_STATUS_UNSPECIFIED NotificationStatus = 0
	NotificationStatus_STATUS_PENDING     NotificationStatus = 1
	NotificationStatus_STATUS_SENT        NotificationStatus = 2
	NotificationStatus_STATUS_FAILED      NotificationStatus = 3
)

// Enum value maps for NotificationStatus.
var (
	NotificationStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_SENT",
		3: "STATUS_FAILED",
	}
	NotificationStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_SENT":        2,
		"STATUS_FAILED":      3,
	}
)

func (x NotificationStatus) Enum() *NotificationStatus {
	p := new(NotificationStatus)
	*p = x
	return p
}

func (x NotificationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_notification_v1_history_proto_enumTypes[0].Descriptor()
}

func (NotificationStatus) Type() protoreflect.EnumType {
	return &file_proto_notification_v1_history_proto_enumTypes[0]
}

func (x NotificationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationStatus.Descriptor instead.
func (NotificationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{0}
}

type GetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_proto_notification_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *GetHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*NotificationRecord  `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_proto_notification_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *GetHistoryResponse) GetRecords() []*NotificationRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *GetHistoryResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_proto_notification_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_proto_notification_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *GetStatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type NotificationRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	SourceService string                 `protobuf:"bytes,5,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	Status        NotificationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=notification.v1.NotificationStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRecord) Reset() {
	*x = NotificationRecord{}
	mi := &file_proto_notification_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRecord) ProtoMessage() {}

func (x *NotificationRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_notification_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRecord.ProtoReflect.Descriptor instead.
func (*NotificationRecord) Descriptor() ([]byte, []int) {
	return file_proto_notification_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NotificationRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationRecord) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NotificationRecord) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *NotificationRecord) GetStatus() NotificationStatus {
	if x != nil {
		return x.Status
	}
	return NotificationStatus_STATUS_UNSPECIFIED
}

func (x *NotificationRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationRecord) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *NotificationRecord) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_notification_v1_history_proto protoreflect.FileDescriptor

const file_proto_notification_v1_history_proto_rawDesc = "" +
	"\n" +
	"#proto/notification/v1/history.proto\x12\x0fnotification.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"i\n" +
	"\x12GetHistoryResponse\x12=\n" +
	"\arecords\x18\x01 \x03(\v2#.notification.v1.NotificationRecordR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\";\n" +
	"\x10GetStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"\x85\x01\n" +
	"\x11GetStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xe4\x02\n" +
	"\x12NotificationRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12%\n" +
	"\x0esource_service\x18\x05 \x01(\tR\rsourceService\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.notification.v1.NotificationStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage*d\n" +
	"\x12NotificationStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x0f\n" +
	"\vSTATUS_SENT\x10\x02\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x032\xbb\x01\n" +
	"\x0eHistoryService\x12U\n" +
	"\n" +
	"GetHistory\x12\".notification.v1.GetHistoryRequest\x1a#.notification.v1.GetHistoryResponse\x12R\n" +
	"\tGetStatus\x12!.notification.v1.GetStatusRequest\x1a\".notification.v1.GetStatusResponseB@Z>github.com/kolbqskq/notification-service/proto/notification/v1b\x06proto3"

var (
	file_proto_notification_v1_history_proto_rawDescOnce sync.Once
	file_proto_notification_v1_history_proto_rawDescData []byte
)

func file_proto_notification_v1_history_proto_rawDescGZIP() []byte {
	file_proto_notification_v1_history_proto_rawDescOnce.Do(func() {
		file_proto_notification_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_notification_v1_history_proto_rawDesc), len(file_proto_notification_v1_history_proto_rawDesc)))
	})
	return file_proto_notification_v1_history_proto_rawDescData
}

var file_proto_notification_v1_history_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_notification_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_notification_v1_history_proto_goTypes = []any{
	(NotificationStatus)(0),       // 0: notification.v1.NotificationStatus
	(*GetHistoryRequest)(nil),     // 1: notification.v1.GetHistoryRequest
	(*GetHistoryResponse)(nil),    // 2: notification.v1.GetHistoryResponse
	(*GetStatusRequest)(nil),      // 3: notification.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 4: notification.v1.GetStatusResponse
	(*NotificationRecord)(nil),    // 5: notification.v1.NotificationRecord
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_notification_v1_history_proto_depIdxs = []int32{
	5, // 0: notification.v1.GetHistoryResponse.records:type_name -> notification.v1.NotificationRecord
	6, // 1: notification.v1.GetStatusResponse.sent_at:type_name -> google.protobuf.Timestamp
	0, // 2: notification.v1.NotificationRecord.status:type_name -> notification.v1.NotificationStatus
	6, // 3: notification.v1.NotificationRecord.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: notification.v1.NotificationRecord.sent_at:type_name -> google.protobuf.Timestamp
	1, // 5: notification.v1.HistoryService.GetHistory:input_type -> notification.v1.GetHistoryRequest
	3, // 6: notification.v1.HistoryService.GetStatus:input_type -> notification.v1.GetStatusRequest
	2, // 7: notification.v1.HistoryService.GetHistory:output_type -> notification.v1.GetHistoryResponse
	4, // 8: notification.v1.HistoryService.GetStatus:output_type -> notification.v1.GetStatusResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_notification_v1_history_proto_init() }
func file_proto_notification_v1_history_proto_init() {
	if File_proto_notification_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_notification_v1_history_proto_rawDesc), len(file_proto_notification_v1_history_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_notification_v1_history_proto_goTypes,
		DependencyIndexes: file_proto_notification_v1_history_proto_depIdxs,
		EnumInfos:         file_proto_notification_v1_history_proto_enumTypes,
		MessageInfos:      file_proto_notification_v1_history_proto_msgTypes,
	}.Build()
	File_proto_notification_v1_history_proto = out.File
	file_proto_notification_v1_history_proto_goTypes = nil
	file_proto_notification_v1_history_proto_depIdxs = nil
}
